# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This is a website.
email: nickkiermaier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to whatever this is.
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
excerpt_separator: <!--more-->


# Build settings
markdown: kramdown
gems:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-paginate-category

# Pagination
paginate: 5
paginate_path: "page:num"

category_dir: "categories"
category_layout: "_layouts/category.html"

# Asset settings
js_location: /assets/js
css_location: /assets/css
img_location: /assets/img
vendor_location: /assets/vendor

include: [_pages]




